name: LinkedIn Post Automation

on:
  schedule:
    - cron: '0 9 * * *'  # Scheduled to run every day at 09:00 UTC
  workflow_dispatch:  # Allows manual trigger through the GitHub UI

jobs:
  post_to_linkedin:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4-beta  # Using pre-release version for Node.js 20 compatibility

    - name: Set up Python
      uses: actions/setup-python@v4.1.0-beta  # Pre-release version for Node.js 20 compatibility
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pandas requests openpyxl

    - name: Run LinkedIn post script
      run: python linkedin_post.py
